INSERT INTO Genres( Name, Description) VALUES (1, 'Fantasy', 'A genre that incorporates imaginative and fantastic themes. These themes usually involve magic, supernatural events, or fantasy worlds.');
INSERT INTO Genres(Name, Description) VALUES (2, 'Romance', 'A genre wherein the plot revolves around the love between two protagonists. This genre usually has a theme that explores an issue within love, including but not limited to: love at first sight, forbidden love, love triangles, and sacrificial love.');
INSERT INTO Genres(Name, Description) VALUES (3, 'Science-Fiction', 'A genre that incorporates hypothetical, science-based themes into the plot of the film. Often, this genre incorporates futuristic elements and technologies to explore social, political, and philosophical issues.');
INSERT INTO Genres(Name, Description) VALUES (4, 'Mystery', 'Centers on a person of authority, usually a detective, that is trying to solve a mysterious crime.');
INSERT INTO Genres(Name, Description) VALUES (5, 'Drama', 'A genre that relies on the emotional and relational development of realistic characters. While Drama film relies heavily on this kind of development, dramatic themes play a large role in the plot as well.');
INSERT INTO Genres(Name, Description) VALUES (6, 'Adventure', 'Adventure film is a genre that revolves around the conquests and explorations of a protagonist. The purpose of the conquest can be to retrieve a person or treasure, but often the main focus is simply the pursuit of the unknown.');
INSERT INTO Genres(Name, Description) VALUES (7, 'Family', 'A genre that is contains appropriate content for younger viewers. Family film aims to appeal not only to children, but to a wide range of ages. While the storyline may appeal to a younger audience, there are components of the film that are geared towards adults- such as witty jokes and humor.');


INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (1, 'Hayao Miyazaki', 'Japanese anime director whose lyrical and allusive works won both critical and popular acclaim.', '1941-01-05', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (2, 'Jean-Pierre Jeunet', 'A self-taught director.', '1953-09-03', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (3, 'Christopher Nolan', 'British film director and writer.', '1970-06-30', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (4, 'Rian Johnson', 'American film director and writer.', '1973-12-17', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (5, 'Greta Gerwig', 'American actress, writer, and director.', '1983-08-14', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (6, 'Ron Clements', 'A an American animator, film director, screenwriter, and film producer', '1953-04-25', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (7, 'Joe Wright', 'An English film director', '1972-08-25', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (8, 'Byron Howard', 'An American animator, character designer, story artist, film director, film producer, and screenwriter.', '1968-12-26', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES (9, 'Marc Webb', 'An American film and music video director', '1974-08-31', null);

INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (1, 'My Neighbor Totoro', 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.', 1, 1, NULL, true);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (2, 'Amelie', 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.', 2, 2, NULL, false);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (3, 'Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', 3, 3, NULL, false);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (4, 'Knives Out', 'A detective investigates the death of the patriarch of an eccentric, combative family.', 4, 4, NULL, false);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (5, 'Little Women', 'Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.', 5, 5, NULL, false);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (6, 'Moana', 'In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana''s island, she answers the Ocean''s call to seek out the Demigod to set things right.', 6, 6, NULL, false);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (7, 'Pride & Prejudice', 'Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class. Can each overcome their own pride and prejudice?', 5, 7, NULL, false);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (8, 'Tangled', 'The magically long-haired Rapunzel has spent her entire life in a tower, but now that a runaway thief has stumbled upon her, she is about to discover the world for the first time, and who she really is.', 8, 8, NULL, false);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (9, '(500) Days of Summer', 'After being dumped by the girl he believes to be his soulmate, hopeless romantic Tom Hansen reflects on their relationship to try and figure out where things went wrong and how he can win her back.', 2, 9, NULL, false);
INSERT INTO Movies(Title, Description,  directorid,imageurl,featured) VALUES (10, 'Spirited Away', 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', 1, 2, NULL, false);

//

INSERT INTO Genres(Name, Description) VALUES ('Fantasy', 'A genre that incorporates imaginative and fantastic themes. These themes usually involve magic, supernatural events, or fantasy worlds.');
INSERT INTO Genres(Name, Description) VALUES ('Romance', 'A genre wherein the plot revolves around the love between two protagonists. This genre usually has a theme that explores an issue within love, including but not limited to: love at first sight, forbidden love, love triangles, and sacrificial love.');
INSERT INTO Genres(Name, Description) VALUES ('Science-Fiction', 'A genre that incorporates hypothetical, science-based themes into the plot of the film. Often, this genre incorporates futuristic elements and technologies to explore social, political, and philosophical issues.');
INSERT INTO Genres(Name, Description) VALUES ('Mystery', 'Centers on a person of authority, usually a detective, that is trying to solve a mysterious crime.');
INSERT INTO Genres(Name, Description) VALUES ('Drama', 'A genre that relies on the emotional and relational development of realistic characters. While Drama film relies heavily on this kind of development, dramatic themes play a large role in the plot as well.');
INSERT INTO Genres(Name, Description) VALUES ('Adventure', 'Adventure film is a genre that revolves around the conquests and explorations of a protagonist. The purpose of the conquest can be to retrieve a person or treasure, but often the main focus is simply the pursuit of the unknown.');
INSERT INTO Genres(Name, Description) VALUES ('Family', 'A genre that is contains appropriate content for younger viewers. Family film aims to appeal not only to children, but to a wide range of ages. While the storyline may appeal to a younger audience, there are components of the film that are geared towards adults- such as witty jokes and humor.');


INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Hayao Miyazaki', 'Japanese anime director whose lyrical and allusive works won both critical and popular acclaim.', '1941-01-05', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Jean-Pierre Jeunet', 'A self-taught director.', '1953-09-03', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Christopher Nolan', 'British film director and writer.', '1970-06-30', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Rian Johnson', 'American film director and writer.', '1973-12-17', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Greta Gerwig', 'American actress, writer, and director.', '1983-08-14', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Ron Clements', 'A an American animator, film director, screenwriter, and film producer', '1953-04-25', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Joe Wright', 'An English film director', '1972-08-25', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Byron Howard', 'An American animator, character designer, story artist, film director, film producer, and screenwriter.', '1968-12-26', null);
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES ('Marc Webb', 'An American film and music video director', '1974-08-31', null);

INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('My Neighbor Totoro', 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.', 1, 1, NULL, true);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Amelie', 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.', 2, 2, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', 3, 3, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Knives Out', 'A detective investigates the death of the patriarch of an eccentric, combative family.', 4, 4, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Little Women', 'Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.', 5, 5, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Moana', 'In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana''s island, she answers the Ocean''s call to seek out the Demigod to set things right.', 6, 6, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Pride & Prejudice', 'Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class. Can each overcome their own pride and prejudice?', 5, 7, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Tangled', 'The magically long-haired Rapunzel has spent her entire life in a tower, but now that a runaway thief has stumbled upon her, she is about to discover the world for the first time, and who she really is.', 8, 8, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('(500) Days of Summer', 'After being dumped by the girl he believes to be his soulmate, hopeless romantic Tom Hansen reflects on their relationship to try and figure out where things went wrong and how he can win her back.', 2, 9, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Spirited Away', 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', 1, 1, NULL, false);

INSERT INTO Genres(Name, Description) VALUES('Animated', 'Animation is a method in which pictures are manipulated to appear as moving images. In traditional animation, images are drawn or painted by hand on transparent celluloid sheets to be photographed and exhibited on film.');
INSERT INTO Genres(Name, Description) VALUES('Comedy', 'Comedy is a genre of film in which the main emphasis is on humor. These films are designed to make the audience laugh through amusement and most often work by exaggerating characteristics for humorous effect.');
INSERT INTO Directors(Name, Bio, Birthyear, Deathyear) VALUES('Jonathan Demme', 'Robert Jonathan Demme was an American director, producer, and screenwriter.', '1944-01-01', '2017-01-01');
INSERT INTO Directors(Name, Bio, Birthyear) VALUES ('Judd Apatow', 'Judd Apatow is an American producer, writer, director, actor and stand-up comedian.', '1967-01-01');
INSERT INTO Movies(Title, Description, genreid, directorid,imageurl,featured) VALUES('Silence of the Lambs','A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',1,1,'silenceofthelambs.png',True);



INSERT INTO Movies(title, description, genreid, directorid, imageurl, featured) VALUES ('My Neighbor Totoro', 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.', 1, 1, NULL, true);
INSERT INTO Movies(title, description, genreid, directorid, imageurl, featured) VALUES ('Amelie', 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.', 2, 2, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', 3, 3, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Knives Out', 'A detective investigates the death of the patriarch of an eccentric, combative family.', 4, 4, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Little Women', 'Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.', 5, 5, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Moana', 'In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana''s island, she answers the Ocean''s call to seek out the Demigod to set things right.', 6, 6, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Pride & Prejudice', 'Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class. Can each overcome their own pride and prejudice?', 5, 7, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Tangled', 'The magically long-haired Rapunzel has spent her entire life in a tower, but now that a runaway thief has stumbled upon her, she is about to discover the world for the first time, and who she really is.', 8, 8, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('(500) Days of Summer', 'After being dumped by the girl he believes to be his soulmate, hopeless romantic Tom Hansen reflects on their relationship to try and figure out where things went wrong and how he can win her back.', 2, 9, NULL, false);
INSERT INTO Movies(Title, Description, genreid, directorid, imageurl, featured) VALUES ('Spirited Away', 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', 1, 1, NULL, false);
